#!/usr/bin/env bash

mkdir -p ./packages/font-glyphs
mkdir -p ./packages/font-otl
cp -a ./font-glyphs-pristine/* ./packages/font-glyphs
cp -a ./font-otl-pristine/* ./packages/font-otl

if [ -z "$1" ]; then
  npm run build ttf::IosevkaCustom
else
  "$@"
fi
