#!/usr/bin/env bash

PUID=${PUID:-1000}
usermod -o -u "$PUID" node

chown -R node:node /home/node /app

runuser -u node -- mkdir -p ./packages/font-glyphs
runuser -u node -- mkdir -p ./packages/font-otl
runuser -u node -- cp -a ./font-glyphs-pristine/* ./packages/font-glyphs
runuser -u node -- cp -a ./font-otl-pristine/* ./packages/font-otl

if [ -z "$1" ]; then
  runuser -u node -- npm run build ttf::IosevkaCustom
else
  runuser -u node -- "$@"
fi
