#!/usr/bin/env bash

IOSEVKA_VERSION=$(curl -L https://api.github.com/repos/be5invis/Iosevka/releases/latest | jq --raw-output '.tag_name')
PROJECT_NAME=$(basename "$PWD")

docker build \
  --pull \
  --build-arg "IOSEVKA_VERSION=${IOSEVKA_VERSION}" \
  --tag "mikewhy/$PROJECT_NAME:$IOSEVKA_VERSION" \
  .

docker tag "mikewhy/$PROJECT_NAME:$IOSEVKA_VERSION" "$PROJECT_NAME:latest"

if [ "$GITHUB_REF" = "refs/heads/main" ]; then
  docker push "mikewhy/$PROJECT_NAME:$IOSEVKA_VERSION"
  docker push "mikewhy/$PROJECT_NAME:latest"
fi
