#!/usr/bin/env bash

IOSEVKA_VERSION=$(curl -L https://api.github.com/repos/be5invis/Iosevka/releases/latest | jq --raw-output '.tag_name')
PROJECT_NAME=$(basename "$PWD")

docker build \
  --pull \
  --build-arg "IOSEVKA_VERSION=${IOSEVKA_VERSION}" \
  --tag "$PROJECT_NAME:$IOSEVKA_VERSION" \
  .

docker tag "$PROJECT_NAME:$IOSEVKA_VERSION" "$PROJECT_NAME:latest"